// This file is dynamically generated by Firebase Studio. Do not edit.

/**
 * Your Firebase project's client-side configuration.
 *
 * This configuration is intended for use in the browser and is not a secret.
 * It is used to initialize the Firebase SDKs.
 *
 * For more information on how to use this, visit:
 * https://firebase.google.com/docs/web/setup#available-libraries
 */
export const firebaseConfig = {
  projectId: 'studio-1044710105-c2081',
  appId: '1:1039949913714:web:8903e0f740c2eb5989aceb',
  apiKey: 'AIzaSyCb69encQoGQp0QR37p5cuhi0yNKwuuAB8',
  authDomain: 'studio-1044710105-c2081.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '1039949913714',
};
