// This file is dynamically generated by Firebase Studio. Do not edit.

/**
 * Your Firebase project's client-side configuration.
 *
 * This configuration is intended for use in the browser and is not a secret.
 * It is used to initialize the Firebase SDKs.
 *
 * For more information on how to use this, visit:
 * https://firebase.google.com/docs/web/setup#available-libraries
 */
export const firebaseConfig = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}'
);
