
// This file is dynamically generated by Firebase Studio. Do not edit.

/**
 * Your Firebase project's client-side configuration.
 *
 * This configuration is intended for use in the browser and is not a secret.
 * It is used to initialize the Firebase SDKs.
 *
 * For more information on how to use this, visit:
 * https://firebase.google.com/docs/web/setup#available-libraries
 */
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};
